[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools>=46.1.0", "setuptools_scm[toml]>=5"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrtools"
dynamic = ["version"]
requires-python = ">=3.11"

[project.dependencies]
numpy       = ">=1.19"
pandas      = ">=1.1"
scipy       = ">=1.5"


[project.optional-dependencies]
rpy2 = [
  "rpy2>=3.5.0",
  "anndata2ri>=0.2"    # for sparseâ€matrix bridging
]

# The test suite needs pytest, numpy, pandas, etc.:
tests = [
  "pytest>=7.0",
  "numpy>=1.19",
  "pandas>=1.5",
  "scipy>=1.8",
  "seaborn>=0.12",
  "rpy2>=3.5.0",
  "anndata2ri>=1.0.0",
]

anndata = [
  "anndata>=0.9",
  "anndata2ri>=1.0.0",
]

[tool.setuptools_scm]
# For smarter version schemes and other configuration options,
# check out https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"

[tool.ruff]
line-length = 120
src = ["src"]
exclude = ["tests"]
lint.extend-ignore = ["F821"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
